name: Verify

on:
  pull_request:

jobs:
  release:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - run: npm ci

      - run: npm test

      - run: npm run-script lint
